In [10]:
!pip install tensorflow
!pip install keras

In [21]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
import numpy as np
np.random.seed(777)

x_data = np.array([[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]])
y_data = np.array([[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]])

# Evaluation our model using this test dataset
x_test = np.array([[2, 1, 1], [3, 1, 2], [3, 3, 4]])
y_test = np.array([[0, 0, 1], [0, 0, 1], [0, 0, 1]])

model = Sequential()
model.add(Dense(3, input_dim=3))
model.add(Activation('softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
             optimizer=SGD(lr=0.1),
             metrics=['accuracy'])

history = model.fit(x_data, y_data, epochs = 200)

predictions = model.predict(x_test)
score = model.evaluate(x_test, y_test)

print('Predictions : ', [np.argmax(prediction) for prediction in predictions])
print('Accuracy : ', score[1])




Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 3)                 12        
_________________________________________________________________
activation_5 (Activation)    (None, 3)                 0         
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________
Epoch 1/200
1/1 [==============================] - 0s 4ms/step - loss: 5.0754 - accuracy: 0.3750
Epoch 2/200
1/1 [==============================] - 0s 3ms/step - loss: 3.0065 - accuracy: 0.3750
Epoch 3/200
1/1 [==============================] - 0s 4ms/step - loss: 1.3795 - accuracy: 0.3750
Epoch 4/200
1/1 [==============================] - 0s 3ms/step - loss: 1.2352 - accuracy: 0.2500
Epoch 5/200
1/1 [==============================] - 0s 2ms/step - loss: 1.1811 - accuracy: 0.2500
Epoch 6/200
1/1 [==================

1/1 [==============================] - 0s 2ms/step - loss: 0.7383 - accuracy: 0.6250
Epoch 79/200
1/1 [==============================] - 0s 4ms/step - loss: 0.7363 - accuracy: 0.6250
Epoch 80/200
1/1 [==============================] - 0s 2ms/step - loss: 0.7344 - accuracy: 0.6250
Epoch 81/200
1/1 [==============================] - 0s 3ms/step - loss: 0.7324 - accuracy: 0.6250
Epoch 82/200
1/1 [==============================] - 0s 2ms/step - loss: 0.7305 - accuracy: 0.6250
Epoch 83/200
1/1 [==============================] - 0s 2ms/step - loss: 0.7287 - accuracy: 0.6250
Epoch 84/200
1/1 [==============================] - 0s 3ms/step - loss: 0.7268 - accuracy: 0.6250
Epoch 85/200
1/1 [==============================] - 0s 2ms/step - loss: 0.7250 - accuracy: 0.6250
Epoch 86/200
1/1 [==============================] - 0s 4ms/step - loss: 0.7232 - accuracy: 0.6250
Epoch 87/200
1/1 [==============================] - 0s 3ms/step - loss: 0.7214 - accuracy: 0.6250
Epoch 88/200
1/1 [===============

1/1 [==============================] - 0s 2ms/step - loss: 0.6293 - accuracy: 0.7500
Epoch 162/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6284 - accuracy: 0.7500
Epoch 163/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6275 - accuracy: 0.7500
Epoch 164/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6266 - accuracy: 0.7500
Epoch 165/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6257 - accuracy: 0.7500
Epoch 166/200
1/1 [==============================] - 0s 966us/step - loss: 0.6248 - accuracy: 0.7500
Epoch 167/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6240 - accuracy: 0.7500
Epoch 168/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6231 - accuracy: 0.7500
Epoch 169/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6222 - accuracy: 0.7500
Epoch 170/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6214 - accuracy: 0.7500
Epoch 171/200
1/1 [===

In [37]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
from sklearn.preprocessing import MinMaxScaler
import numpy as np
np.random.seed(777)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

#정규화
scaler = MinMaxScaler(feature_range = (0, 1))
xy = scaler.fit_transform(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

model = Sequential()
model.add(Dense(1, input_dim = 4))
model.add(Activation('linear'))

model.summary()

model.compile(loss = 'mse',
             optimizer = 'sgd',
             metrics = ['accuracy'])

history = model.fit(x_data, y_data, epochs = 100)

predictions = model.predict(x_data)
score = model.evaluate(x_data, y_data)

print('Predictions : ', predictions)
print('Cost : ', score[0])


[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 1)                 5         
_________________________________________________________________
activation_15 (Activation)   (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
1/1 [==============================] - 0s 5m

1/1 [==============================] - 0s 2ms/step - loss: 0.0952 - accuracy: 0.2500
Epoch 74/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0945 - accuracy: 0.2500
Epoch 75/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0939 - accuracy: 0.2500
Epoch 76/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0932 - accuracy: 0.2500
Epoch 77/100
1/1 [==============================] - 0s 4ms/step - loss: 0.0926 - accuracy: 0.2500
Epoch 78/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0920 - accuracy: 0.2500
Epoch 79/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0914 - accuracy: 0.2500
Epoch 80/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0908 - accuracy: 0.2500
Epoch 81/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0902 - accuracy: 0.2500
Epoch 82/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0896 - accuracy: 0.2500
Epoch 83/100
1/1 [===============